services:
  influxdb:
    image: influxdb:latest
    ports:
      - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    image: chronograf:latest
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  data-reader:
    build:
      context: ./
      dockerfile: ./data-reader/Dockerfile
    image: "data-reader"
    ports:
      - ${DATA_READER_PORT}:${DATA_READER_PORT}
    restart: always
    env_file:
      - .env
    depends_on:
      - influxdb
  arduino-client:
    build:
      context: ./
      dockerfile: ./arduino-client/Dockerfile
    image: "arduino-client"
    ports:
      - 4173:4173
    restart: always
    env_file:
      - .env
    depends_on:
      - data-reader
  # bluetooth-node:
  #   build:
  #     context: ./
  #     dockerfile: ./bluetooth-node/Dockerfile
  #   image: "bluetooth-node"
  #   ports:
  #     - ${BLUETOOTH_NODE_PORT}:${BLUETOOTH_NODE_PORT}
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - influxdb
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
