services:
  data-reader:
    build:
      context: ./
      dockerfile: ./data-reader/Dockerfile
    image: "data-reader"
    ports:
      - ${BLUETOOTH_NODE_PORT}:${BLUETOOTH_NODE_PORT}
    restart: always
    env_file:
      - .env
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - /mnt/svl/influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

  # Use the influx cli to set up an influxdb instance.
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - /mnt/svl/influxdb2:/var/lib/influxdb2:rw
      - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
    environment:
      # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myusername
      - DOCKER_INFLUXDB_INIT_PASSWORD=passwordpasswordpassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb

  # telegraf:
  #   image: telegraf
  #   links:
  #     - influxdb
  #   volumes:
  #     # Mount for telegraf config
  #     - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
  #   env_file:
  #     - ./influxv2.env
  #   environment:
  #     - DOCKER_INFLUXDB_INIT_ORG=myorg
  #     - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
  #     - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
  #   depends_on:
  #     - influxdb_cli

volumes:
  influxdb2:

networks:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
